---
title: "FAQ for StepReg"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{FAQ for StepReg}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Below are some Frequently Asked Questions about StepReg. If you have a question that you think would fit well here please open an issue[here](https://github.com/JunhuiLi1017/StepReg/issues/new).

# Frequently Asked Questions

**Q: How do I install StepReg efficiently?**  
A: You can install StepReg using the following command:

```r
pak::pkg_install("StepReg")
```

or

```r
pak::pkg_install("JunhuiLi1017/StepReg")
```

or

```r
install.packages("StepReg")
```

or

```r
devtools::install_github("JunhuiLi1017/StepReg")
```
we recommend using `pak::pkg_install("StepReg")` or `pak::pkg_install("JunhuiLi1017/StepReg")` to install StepReg to avoid the dependency issues.

**Q: How to use StepReg?**  
A: You can refer to the [StepReg vignette](https://CRAN.R-project.org/package=StepReg/vignettes/StepReg.html) for detailed examples.

**Q: How to use the interactive Shiny application?**  
A: You can refer to the [StepReg Shiny application](https://junhuili1017.shinyapps.io/StepReg/) for detailed examples.

**Q: I encounter a missing system libraries error when installing StepReg. What should I do?**  
A: Some dependencies of StepReg require additional system libraries to be installed on your computer. If you see an error message about missing system packages, you may need to manually install them using your system package manager.

For common dependencies, you may need to install:

- cairo-devel (required for gdtools)
- ImageMagick-c++-devel and ImageMagick-devel (required for magick)
- libwebp-devel (required for ragg)
- X11 library (required for graphics on macOS): If the X11 library is missing (often required for graphics on macOS), please install XQuartz first.

installation examples:

Ubuntu/Debian:
```sh
sudo apt-get install libcairo2-dev libwebp-dev libmagick++-dev
```

Red Hat/CentOS:
```sh
sudo yum install cairo-devel libwebp-devel ImageMagick-c++-devel ImageMagick-devel
```

macOS:
You can use Homebrew to install the dependencies (cairo, imagemagick, and webp):
```sh
brew install cairo imagemagick webp
```
