---
title: "StepReg report"
output: html_document
date: today
params:
  modelSelection: NA
  selectionPlot: NA
  modelVote: NA
---

```{r include = FALSE}
knitr::opts_chunk$set(echo=FALSE)
library(ggplot2)
library(stringr)
library(flextable)
```

## {.tabset}

### Statistics

**Statistics of Variable Selection:**

```{r comment = NA}
params$modelSelection
nmetric <- length(unlist(str_split(params$modelSelection[[1]][3,2], "&")))
strategies <- length(unlist(str_split(params$modelSelection[[1]][2,2], "&")))
```

### Visualization

**Visualization of Variable Selection:**
#### forward strategy
```{r comment = NA, fig.width = 10 * 2, fig.height = 10}
params$selectionPlot$forward$summary
```
```{r comment = NA, fig.width = 10, fig.height = 8 * nmetric}
params$selectionPlot$forward$detail
```
#### backward strategy
```{r comment = NA, fig.width = 10 * 2, fig.height = 10}
params$selectionPlot$backward$summary
```
```{r comment = NA, fig.width = 10, fig.height = 8 * nmetric}
params$selectionPlot$backward$detail
```
#### bidireciton strategy
```{r comment = NA, fig.width = 10 * 2, fig.height = 10}
params$selectionPlot$bidirection$summary
```
```{r comment = NA, fig.width = 10, fig.height = 8 * nmetric}
params$selectionPlot$bidirection$detail
```
#### subset strategy
```{r comment = NA, fig.width = 10 * 2, fig.height = 10}
params$selectionPlot$subset$summary
```
```{r comment = NA, fig.width = 10, fig.height = 8 * nmetric}
params$selectionPlot$subset$detail
```


### Models Vote

**Model Selection by Vote Across All Combinations of Strategy and Metric:**

```{r comment = NA}
flextable(params$modelVote)
```